# Generated by Django 5.0.3 on 2024-04-02 13:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_remove_article_image_alter_article_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 4, 2, 13, 0, 12, 696404, tzinfo=datetime.timezone.utc)),
        ),
    ]
